# Sorting

In [1]:
import time
import numpy as np
np.random.seed(0)

In [2]:
data = np.random.randint(1,10000,17000)

### Insertion Sort

In [3]:
def insertion_sort(arr):
    start = time.time()
    for i in range(1,len(arr)):  #starts at i=1 (for (i=1,i<n,i++))
        selection=arr[i]
        j=i-1
        while j >=0 and selection<arr[j]:
            arr[j+1]=arr[j]
            j=j-1
        arr[j+1]=selection
    end = time.time()
    print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a size of ", len(arr))
    return arr

In [4]:
arr=insertion_sort(data)

The time of execution of above program is : 51252.4139881134 ms for a size of  17000


In [5]:
arr

array([   1,    1,    1, ..., 9999, 9999, 9999])

### Merge Sort

In [6]:
def merge(arr,left,right):
    #Merge, in this method I applied the actual merging.
    #What's the complexity in space for Merge sort?
    new_arr = np.zeros(len(arr))
    len_left = len(left)
    len_right = len(right)
    ind_l=ind_r=ind_arr=0
    while ind_l < len_left and ind_r < len_right: #after divided, go through each half and compare the number by index
        if left[ind_l] <= right[ind_r]:   #if number in left[ind_l] is the lesser, add it to the array in pos k
            new_arr[ind_arr] = left[ind_l]
            ind_l += 1
        else:
            new_arr[ind_arr] = right[ind_r]  #if number in right[ind_r] is the lesser, add it to the array in pos k
            ind_r += 1
#         print("new_arr",new_arr)
        ind_arr += 1
            
    while ind_l < len(left):
        new_arr[ind_arr] = left[ind_l]
        ind_l += 1
        ind_arr += 1
#         print("new_arr",new_arr)

    while ind_r < len(right):
        new_arr[ind_arr] = right[ind_r]
        ind_r += 1
        ind_arr += 1
#         print("new_arr",new_arr)

    return new_arr

In [7]:
def merge_sort(arr):
    #This method will divide the array
    #print(arr)
    length=len(arr)
    if length > 1:
        mid=length//2
        left=merge_sort(arr[:mid])
        right=merge_sort(arr[mid:])
        return merge(arr,left,right)
    else:
        return arr

In [8]:
#This method is just to calculate the time, if you don't need it, don't worry
def merge_algorithm(arr):
    start = time.time()
    arr=merge_sort(arr)
    end = time.time()
    print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a size of ", len(arr))
    return arr

In [9]:
data = np.random.randint(1,10000,17000)

In [10]:
sorted_data=merge_algorithm(data)
sorted_data

The time of execution of above program is : 229.19201850891113 ms for a size of  17000


array([1.000e+00, 3.000e+00, 4.000e+00, ..., 9.998e+03, 9.998e+03,
       9.998e+03])

### Complexity Analysis:

* Space complexity = $O(N)$

The space consumed by dividing and storing the elements of the array is the total number of elements present in the array.

* Time complexity = $O(n*log(n))$

In the merge_sort method, the array is divided in two each time the method is called. If the total time for the size $n$ array is $cn$, this division is the equivalent to doing the number of problems by the time for each problem.

The problem will be then divided into log(n) levels which can be visualized with a division tree:

```
^                 cn                      level 1: cn
|               /    \
|           cn/2      cn/2                level 2: cn/2+cn/2=cn
log(n)     /    \     /    \
|       cn/4   cn/4  cn/4   cn/4          level 3: 4*cn/4=cn
|        / \   / \   / \    / \ 
|       ...
|      |  |  |  |  |  |  |...|  |
v      c  c  c  c  c  c  c   c  c         c+c+c+...+c=cn
```

As the merge process has linear complexity $(n)$, for n elements, the division and merge stages will be $n*log(n)$

Then, the complexity of the merge sort is $O(n*log(n))$


### Algorithm of your choice

Now implement another algorithm, anyone works. Use the same size of data.

In [11]:
def partition(arr,low,high): 
    pivot=arr[high]
    i=low-1
    j=low
    #print("partition",f"pivot: {pivot}",f"i: {i}", f"j: {j}", f"arr: {arr}")
    while j <= high-1:
        if arr[j] < pivot:
            i+=1
            temp=arr[i]
            arr[i]=arr[j]
            arr[j]=temp
        j+=1
        #print(f"          pivot: {pivot}",f"i: {i}", f"j: {j}",f"arr: {arr}")
        
    temp=arr[i+1]
    arr[i+1]=arr[high]
    arr[high]=temp
    return i+1

In [12]:
def quicksort(arr,low,high):
    if low<high:
        #print("quicksort",arr)
        part=partition(arr,low,high)
        quicksort(arr,low,part-1)
        quicksort(arr,part+1,high)

In [13]:
def quicksort_algorithm(arr):
    start = time.time()
    quicksort(arr,0,len(arr)-1)
    end = time.time()
    print("The time of execution of above program is :", (end-start) * 10**3, "ms", "for a size of ", len(arr))
    return arr

In [14]:
data = np.random.randint(1,10000,17000)

In [15]:
quicksort_algorithm(data)

The time of execution of above program is : 208.87088775634766 ms for a size of  17000


array([   1,    1,    2, ..., 9996, 9998, 9998])

### Conclusions

So, the algorithm matters! Even when the result is the same, the time it takes is important. We are in the era of Big Data, if we are not careful, some processing might take centuries!